name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: |
        Feature '…' is not working correctly. I expect '…' to happen, but '…' happens instead.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '…'
        2. Click on '…'
        3. Scroll down to '…'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment info
      description: Specify the system you encounter the bug on.
      placeholder: |
        - Package version
        - Browser(s) are you seeing the problem on
        - Device you are using and operating system
    validations:
      required: false
  - type: textarea
    attributes:
      label: Relevant log output
      description: Copy and paste any relevant log output. This will be automatically formatted into code, so there is no need for backticks.
      render: shell
  - type: textarea
    attributes:
      label: Additional context
      description: Provide additional information about the problem here, e.g., screenshots and screencasts.
    validations:
      required: false
